import org.antlr.v4.runtime.tree.ParseTreeVisitor;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class main {
    public static void main(String[] args) throws IOException{

		// we expect exactly one argument: the name of the input file
		if (args.length != 1) {
		    System.err.println("\n");
		    System.err.println("hwsim Interpreter\n");
		    System.err.println("=================\n\n");
		    System.err.println("Please give as input argument a filename\n");
		    System.exit(-1);
		}
		String filename = args[0];

		// open the input file
		CharStream input = CharStreams.fromFileName(filename);
		    //new ANTLRFileStream (filename); // depricated
		
		// create a lexer/scanner
		hwsimLexer lex = new hwsimLexer(input);
		
		// get the stream of tokens from the scanner
		CommonTokenStream tokens = new CommonTokenStream(lex);
		
		// create a parser
		hwsimParser parser = new hwsimParser(tokens);
		
		// and parse anything from the grammar for "start"
		ParseTree parseTree = parser.start();

		// Construct an interpreter and run it on the parse tree
		Interpreter interpreter = new Interpreter();
		AST result = interpreter.visit(parseTree);
		System.out.println("The result is: " + result);
    }
}

// We write an interpreter that implements interface
// "hwsimVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Integer.

class Interpreter extends AbstractParseTreeVisitor<Expr> implements hwsimVisitor<Expr> {

    	if (ctx.up.getText().equals("update")) {
    		return visit(ctx.e.up);
    	}
    	return visit(ctx.e);
    	
    };
    public Expr visitStart(hwsimParser.StartContext ctx){
    
    public Expr visitNegation(hwsimParser.NegationContext ctx) {
    	return new Negation(visit(ctx.c1));
    };

    public Expr visitConjunction(hwsimParser.ConjunctionContext ctx) {
    	return new Conjunction(visit(ctx.c1), visit(ctx.c2));
    };

    public Expr visitDisjunction(hwsimParser.DisjunctionContext ctx) {
    	return new Disjunction(visit(ctx.c1), visit(ctx.c2));
    };

    public Expr visitVariable(hwsimParser.VariableContext ctx) {
    	return new Variable(ctx.x.getText());
    };

    public Expr visitParentheses(hwsimParser.ParenthesesContext ctx) {
    	return visit(ctx.c1);
    };


}

